db:
  image: mysql:8.0
  container_name: messaging_db
  restart: always
  environment:
    MYSQL_USER: myuser
    MYSQL_PASSWORD: mypassword
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DB: messaging_db # <-- use MYSQL_DB
  ports:
    - "3306:3306"
  volumes:
    - db_data:/var/lib/mysql
